import js from '@eslint/js';

export default [
  {
    ignores: ['dist/**/*', 'node_modules/**/*', 'android/**/*'],
  },
  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        navigator: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        Uint8Array: 'readonly',
        ArrayBuffer: 'readonly',
        PDFLib: 'readonly',
        confetti: 'readonly',
        JSZip: 'readonly',
        pdfjsLib: 'readonly',
        jspdf: 'readonly',
        initDropZone: 'readonly',
        handleFiles: 'readonly',
        showError: 'readonly',
        validateFileSize: 'readonly',
        renderFileList: 'readonly',
        showProgress: 'readonly',
        downloadFile: 'readonly',
        showSuccess: 'readonly',
        hideProgress: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        Worker: 'readonly',
        indexedDB: 'readonly',
        location: 'readonly',
        process: 'readonly',
        module: 'readonly',
        exports: 'writable',
        fileSizeDisplay: 'readonly',
        formatBytes: 'readonly',
        renderPdfThumbnail: 'readonly',
        alert: 'readonly',
        pageCountDisplay: 'readonly',
        importScripts: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        Promise: 'readonly',
        Math: 'readonly',
        Response: 'readonly',
        VanillaTilt: 'readonly',
        tsParticles: 'readonly',
        gsap: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      'no-undef': 'error',
      'no-empty': 'off',
      'no-redeclare': 'off',
    },
  },
];
