import { ICONS } from "../ui/icons.js";

export const toolsList = [
  {
    id: 'merge',
    title: 'Merge PDF',
    icon: ICONS.merge,
    desc: 'Combine multiple PDFs into one',
    cat: 'organize',
  },
  {
    id: 'split',
    title: 'Split PDF',
    icon: ICONS.split,
    desc: 'Extract pages from your PDF',
    cat: 'organize',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    icon: ICONS.compress,
    desc: 'Reduce file size without losing quality',
    cat: 'optimize',
  },
  {
    id: 'rotate',
    title: 'Rotate PDF',
    icon: ICONS.rotate,
    desc: 'Rotate pages to correct orientation',
    cat: 'edit',
  },
  {
    id: 'reorder',
    title: 'Reorder PDF',
    icon: ICONS.reorder,
    desc: 'Change the order of PDF pages',
    cat: 'organize',
  },
  {
    id: 'delete-pages',
    title: 'Delete Pages',
    icon: ICONS.delete_pages,
    desc: 'Remove unwanted pages',
    cat: 'organize',
  },
  {
    id: 'extract-pages',
    title: 'Extract Pages',
    icon: ICONS.extract_pages,
    desc: 'Get specific pages as a new PDF',
    cat: 'organize',
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    icon: ICONS.image_to_pdf,
    desc: 'Convert JPG/PNG to PDF',
    cat: 'convert',
  },
  {
    id: 'pdf-to-image',
    title: 'PDF to Image',
    icon: ICONS.pdf_to_image,
    desc: 'Convert PDF pages to JPG',
    cat: 'convert',
  },
  {
    id: 'protect',
    title: 'Protect PDF',
    icon: ICONS.protect,
    desc: 'Add password to your PDF',
    cat: 'security',
  },
  {
    id: 'unlock',
    title: 'Unlock PDF',
    icon: ICONS.unlock,
    desc: 'Remove password from PDF',
    cat: 'security',
  },
  {
    id: 'watermark',
    title: 'Watermark',
    icon: ICONS.watermark,
    desc: 'Stamp text on your PDF',
    cat: 'edit',
  },
  {
    id: 'add-page-numbers',
    title: 'Page Numbers',
    icon: ICONS.add_page_numbers,
    desc: 'Insert page numbers',
    cat: 'edit',
  },
  {
    id: 'add-blank-page',
    title: 'Add Blank Page',
    icon: ICONS.add_blank_page,
    desc: 'Insert blank pages anywhere',
    cat: 'edit',
  },
  {
    id: 'crop-resize',
    title: 'Crop & Resize',
    icon: ICONS.crop_resize,
    desc: 'Adjust margins and dimensions',
    cat: 'optimize',
  },
];
